services:
  - type: web
    name: yappy-ai-db
    env: python
    buildCommand: pip install -r requirements_complete.txt
    startCommand: python app_db.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APP_VERSION
        value: database
        
databases:
  - name: yappy-postgres
    databaseName: yappy
    user: yappy