services:
  - type: web
    name: yappy-ai
    runtime: python
    buildCommand: pip install -r requirements_minimal.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /health