services:
  - type: web
    name: yappy-ai
    env: python
    buildCommand: pip install -r requirements_minimal.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0