name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/agentic-seek-front/package-lock.json
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install frontend dependencies
      working-directory: frontend/agentic-seek-front
      run: npm ci
      
    - name: Build frontend
      working-directory: frontend/agentic-seek-front
      run: npm run build
      
    - name: Install backend dependencies
      run: pip install -r requirements.txt
      
    - name: Run tests (if available)
      run: |
        if [ -f "tests/test_*.py" ]; then
          python -m pytest tests/ -v
        else
          echo "No tests found, skipping test step"
        fi
      continue-on-error: true
      
    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: railway-app/railway-deploy@v1
      with:
        token: ${{ secrets.RAILWAY_TOKEN }}
        service: ${{ secrets.RAILWAY_SERVICE_ID }}
        
    - name: Comment deployment status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Deployment preview will be available after merge to main branch'
          })